### ISSUE TITLE
error while installing with sudo pip

### ISSUE THREAD

**Issue by LucaPaterlini** [FoteinosMerg/pymerkle#1]
100% |████████████████████████████████| 61kB 1.1MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-iEVtr_/pymerkle/setup.py", line 3, in <module>
        import pymerkle
      File "pymerkle/__init__.py", line 1, in <module>
        from .tree_tools import merkle_tree
      File "pymerkle/tree_tools.py", line 17
        hash_type='sha256',
                ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-iEVtr_/pymerkle/

**Comment by LucaPaterlini** [comment]
thanks, I have installed it and added to the set of different implentations of the merkle tree...

I am tring to standardize it and so far I have foud more the 6 different implentations
